version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "[github-actions] "
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "[npm] "
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
